package kr.danta.core.diplomacy;
import kr.danta.core.state.GameState;import kr.danta.core.nation.VassalPolicyService;import kr.danta.core.nation.VassalRelation;import java.util.*;
/** DEV-091 war participation. Direct alliances auto-enter only at declaration; their alliances do not chain. */
public final class WarService {
 private final GameState gameState; private final DiplomacyService diplomacy; private final VassalPolicyService vassalPolicy; private final Map<UUID,War> wars=new LinkedHashMap<>();
 public WarService(GameState gameState,DiplomacyService diplomacy){this(gameState,diplomacy,null);} public WarService(GameState gameState,DiplomacyService diplomacy,VassalPolicyService vassalPolicy){this.gameState=Objects.requireNonNull(gameState);this.diplomacy=Objects.requireNonNull(diplomacy);this.vassalPolicy=vassalPolicy;}
 public synchronized War declareWar(String attacker,String defender){requireNation(attacker);requireNation(defender);if(attacker.equals(defender))throw new IllegalArgumentException("same nation war");if(hasActiveWarBetween(attacker,defender))throw new IllegalStateException("active war already exists between nations");if(vassalPolicy!=null&&!vassalPolicy.canDeclareWar(attacker,defender))throw new IllegalStateException("vassal cannot declare war on overlord");if(diplomacy.status(attacker,defender)==DiplomaticStatus.ALLIANCE)throw new IllegalStateException("cannot declare war on alliance");War w=new War(UUID.randomUUID(),attacker,defender);wars.put(w.warId(),w);diplomacy.setStatus(attacker,defender,DiplomaticStatus.WAR);List<String> attackerAllies=directAllies(attacker);List<String> defenderAllies=directAllies(defender);for(String ally:attackerAllies) if(!w.participates(ally)&&!defenderAllies.contains(ally)) joinInternal(w,ally,WarSide.ATTACKER);for(String ally:defenderAllies) if(!w.participates(ally)) joinInternal(w,ally,WarSide.DEFENDER);return w;}
 public synchronized War declareIndependenceWar(String vassal,String overlord){requireNation(vassal);requireNation(overlord);if(vassal.equals(overlord))throw new IllegalArgumentException("same nation war");if(hasActiveWarBetween(vassal,overlord))throw new IllegalStateException("active war already exists between nations");if(vassalPolicy==null||vassalPolicy.canDeclareWar(vassal,overlord))throw new IllegalStateException("independence war requires vassal-overlord relation");if(diplomacy.status(vassal,overlord)==DiplomaticStatus.ALLIANCE)throw new IllegalStateException("cannot declare war on alliance");War w=new War(UUID.randomUUID(),vassal,overlord);wars.put(w.warId(),w);diplomacy.setStatus(vassal,overlord,DiplomaticStatus.WAR);return w;}
 public synchronized Optional<War> findBetween(String initiator,String target){return wars.values().stream().filter(w->w.initiatorNationId().equals(initiator)&&w.targetNationId().equals(target)).findFirst();}
 public synchronized boolean hasActiveWarBetween(String a,String b){return wars.values().stream().anyMatch(w->(w.initiatorNationId().equals(a)&&w.targetNationId().equals(b))||(w.initiatorNationId().equals(b)&&w.targetNationId().equals(a)));}
 public synchronized void endWar(UUID warId){War w=requireWar(warId);for(String a:w.attackers())for(String d:w.defenders())if(diplomacy.status(a,d)==DiplomaticStatus.WAR)diplomacy.setStatus(a,d,DiplomaticStatus.NEUTRAL);wars.remove(warId);}
 public synchronized War supportJoin(UUID warId,String nationId,WarSide side){War w=requireWar(warId);requireNation(nationId);if(vassalPolicy!=null&&!vassalPolicy.canSupportJoin(nationId))throw new IllegalStateException("vassal cannot independently support-join war");joinInternal(w,nationId,side);return w;}
 public synchronized List<War> wars(){return List.copyOf(wars.values());} public synchronized Optional<War> find(UUID id){return Optional.ofNullable(wars.get(id));}
 private void joinInternal(War w,String nation,WarSide side){if(w.participates(nation))throw new IllegalStateException("nation already participates");for(String opponent:(side==WarSide.ATTACKER?w.defenders():w.attackers())) if(diplomacy.status(nation,opponent)==DiplomaticStatus.ALLIANCE)throw new IllegalStateException("cannot join against alliance");w.join(nation,side);for(String opponent:(side==WarSide.ATTACKER?w.defenders():w.attackers())) diplomacy.setStatus(nation,opponent,DiplomaticStatus.WAR);}
 private List<String> directAllies(String nation){return diplomacy.relationsOf(nation).stream().filter(r->r.status()==DiplomaticStatus.ALLIANCE).map(r->r.nationAId().equals(nation)?r.nationBId():r.nationAId()).toList();}
 private War requireWar(UUID id){War w=wars.get(id);if(w==null)throw new IllegalArgumentException("war not found");return w;} private void requireNation(String id){if(!gameState.hasNation(id))throw new IllegalArgumentException("nation does not exist: "+id);}
}
